version: 0.0
os: linux
files:
  - source: scripts/start_docker.sh
    destination: /home/ec2-user/app/scripts/start_docker.sh
  - source: scripts/docker_compose_up.sh
    destination: /home/ec2-user/app/scripts/docker_compose_up.sh
hooks:
  BeforeInstall:
    - location: scripts/remove_existing_start_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/docker_compose_up.sh
      timeout: 300
      runas: root
