# Generated by Django 4.2.6 on 2023-11-16 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-departure']},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
