# Generated by Django 4.2.6 on 2023-11-16 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_trip_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
    ]
